name: Conhecendo o Output do Github Actions
# Nome de execução da Action
run-name: Exemplo Workflow para output, executado por ${{ github.actor }}
on:
    push:
        branches: ["main"]
    workflow_dispatch:
jobs:
    gerando_output:
        runs-on: ubuntu-latest
        steps:
            - name: Gerando Output com Shell
              id: exemplo-output
              run: |
                ACTION_RANDOM=$(($RANDOM))
                echo action_random=$ACTION_RANDOM >> $GITHUB_OUTPUT

            - name: Exibindo o Output da Actions exemplo-output
              run: echo "${{ steps.exemplo-output.outputs.action_random }}"

            - name: Gerador de Senha Randomica
              id: generatedpassword
              uses: aammirmirza/RandomPasswordGenerator@v1.1
              with:
                length: 15

            - name: Exibindo o Output da Actions generatedpassword
              run: echo "${{ steps.generatedpassword.outputs.password }}"
