name: Conhecendo o Output do Github Actions
# Nome de execução da Action
run-name: Exemplo Workflow para output, executado por ${{ github.actor }}
on:
    push:
        branches: ["main"]
    workflow_dispatch:
jobs:
    gerando_output:
        runs-on: ubuntu-latest
        steps:
            - name: Gerando Output com Shell
              id: exemplo-output
              run: |
                ACTION_RANDOM=$(($RANDOM))
                echo action_random=$ACTION_RANDOM >> $GITHUB_OUTPUT

            - name: Exibindo o Output da Actions exemplo-output
              run: echo "${{ steps.exemplo-output.outputs.action_random }}"

