name: Conhecendo o Output do Github Actions
# Nome de execução da Action
run-name: Exemplo Workflow para output, executado por ${{ github.actor }}
on:
    push:
        branches: ["main"]
    workflow_dispatch:
jobs:
    gerando_output_nivel_actions:
        runs-on: ubuntu-latest
        outputs:
            outputs-shell: ${{ steps.shell.outputs.action_random }}
            outputs-generatedpassword: ${{ steps.generatedpassword.outputs.password }}
        steps:
            - name: Gerando Output com Shell
              id: shell
              run: |
                ACTION_RANDOM=$(($RANDOM))
                echo action_random=$ACTION_RANDOM >> $GITHUB_OUTPUT

            - name: Exibindo o Output da Actions exemplo-output
              run: echo "${{ steps.shell.outputs.action_random }}"

            - name: Gerador de Senha Randomica
              id: generatedpassword
              uses: aammirmirza/RandomPasswordGenerator@v1.1
              with:
                length: 60

            - name: Exibindo o Output da Actions generatedpassword
              run: echo "${{ steps.generatedpassword.outputs.password }}"
    exibindo_valores_outputs:
        needs: [gerando_output_nivel_actions]
        runs-on: ubuntu-latest
        steps:
            - name: Exibindo os Outputs do gerando_output_nivel_actions
              run: |
                echo "Output Shell: ${{ needs.gerando_output_nivel_actions.outputs.outputs-shell }}"
                echo "Output Gerador Password: ${{ needs.gerando_output_nivel_actions.outputs.outputs-generatedpassword }}"